"""empty message

Revision ID: 1e1daa95f673
Revises: 8eac699b4ae7
Create Date: 2024-11-19 19:29:12.743817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1daa95f673'
down_revision = '8eac699b4ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=True))

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
