"""empty message

Revision ID: 4c8d14b68070
Revises: 1e1daa95f673
Create Date: 2024-11-19 19:42:10.625807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c8d14b68070'
down_revision = '1e1daa95f673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('mail', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('street', sa.Integer(), nullable=True))
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('date_of_joining',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('employee_email')
        batch_op.drop_column('employee_phone')
        batch_op.drop_column('employee_name')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('mail', sa.String(length=50), nullable=False))
        batch_op.drop_column('member_mail')
        batch_op.drop_column('member_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('member_mail', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('mail')
        batch_op.drop_column('name')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('employee_phone', mysql.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('employee_email', mysql.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('date_of_joining',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('street')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('mail')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
